version: 2
updates:
  ########
  # main #
  ########
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 25
    target-branch: main
    ignore:
      # we will always manually update ES dependencies to minor or major releases
      # as we need to sync with the other teams before doing that
      - dependency-name: org.elasticsearch.client:*
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # After updating to Jacoco 0.8.9 we ran into the issue that our smoke tests on macOS kept
      # failing as it couldn't resolve all of Jacoco's dependencies. It's not quite clear why this
      # happened, but we could identify that it started after updating to this patch version. We
      # have reverted this patch version for now. To make sure dependabot won't update it again, we
      # have added 0.8.9 to the ignored versions.
      - dependency-name: org.jacoco:*
        versions: [ 0.8.9 ]

  # Enable version updates for the go client
  - package-ecosystem: "gomod"
    directory: "clients/go"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(go): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: main

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: main

  ##############
  # stable/8.2 #
  ##############
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 25
    target-branch: "stable/8.2"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # After updating to Jacoco 0.8.9 we ran into the issue that our smoke tests on macOS kept
      # failing as it couldn't resolve all of Jacoco's dependencies. It's not quite clear why this
      # happened, but we could identify that it started after updating to this patch version. We
      # have reverted this patch version for now. To make sure dependabot won't update it again, we
      # have added 0.8.9 to the ignored versions.
      - dependency-name: org.jacoco:*
        versions: [ 0.8.9 ]
    allow:
      # Allow only production dependency updates for maintenance branches
      - dependency-type: "production"

  # Enable version updates for the go client
  - package-ecosystem: "gomod"
    directory: "clients/go"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(go): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.2"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.2"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  ##############
  # stable/8.1 #
  ##############
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 25
    target-branch: "stable/8.1"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # After updating to Jacoco 0.8.9 we ran into the issue that our smoke tests on macOS kept
      # failing as it couldn't resolve all of Jacoco's dependencies. It's not quite clear why this
      # happened, but we could identify that it started after updating to this patch version. We
      # have reverted this patch version for now. To make sure dependabot won't update it again, we
      # have added 0.8.9 to the ignored versions.
      - dependency-name: org.jacoco:*
        versions: [ 0.8.9 ]
    allow:
      # Allow only production dependency updates for maintenance branches
      - dependency-type: "production"

  # Enable version updates for the go client
  - package-ecosystem: "gomod"
    directory: "clients/go"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(go): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.1"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.1"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  ##############
  # stable/8.0 #
  ##############
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 25
    target-branch: "stable/8.0"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # After updating to Jacoco 0.8.9 we ran into the issue that our smoke tests on macOS kept
      # failing as it couldn't resolve all of Jacoco's dependencies. It's not quite clear why this
      # happened, but we could identify that it started after updating to this patch version. We
      # have reverted this patch version for now. To make sure dependabot won't update it again, we
      # have added 0.8.9 to the ignored versions.
      - dependency-name: org.jacoco:*
        versions: [ 0.8.9 ]
    allow:
      # Allow only production dependency updates for maintenance branches
      - dependency-type: "production"

  # Enable version updates for the go client
  - package-ecosystem: "gomod"
    directory: "clients/go"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(go): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.0"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    target-branch: "stable/8.0"
    ignore:
      # Ignore major and minor updates, for stable branches we only want to get patches
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
