status = [
    "Test summary",
]

required_approvals = 1

delete_merged_branches = true

commit_title = "merge: ${PR_REFS}"

# Also cuts the marker, not just after
cut_body_after = "<!-- Cut-off marker"
