steps:
# Write the latest commit message to a file in the workspace.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'git log -1 --format="%s%n%n%b%nSource-Link: https://github.com/googleapis/google-cloud-java/commit/%H" > post-processor-changes.txt'
# Build the docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'gcr.io/cloud-devrel-public-resources/owlbot-java-monorepo:$SHORT_SHA',
          '-t', 'gcr.io/cloud-devrel-public-resources/owlbot-java-monorepo:latest',
          '-f', 'owl-bot-postprocessor/Dockerfile', 'owl-bot-postprocessor' ]
# Push the docker image.
images:
- gcr.io/cloud-devrel-public-resources/owlbot-java-monorepo:$SHORT_SHA
- gcr.io/cloud-devrel-public-resources/owlbot-java-monorepo:latest
