name: Assign Issue to Project

on:
  push:
    branches: [ helidon ]






jobs:
  Assign-Issue-To-Backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: etc/scripts/actions/assign-issue-to-project.sh $GITHUB_REPOSITORY ${{ github.event.issue.number }} Backlog Triage
