name: CI

on:
  push:
    branches: [ shedlock ]





jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '20']
        # Kotlin needs access to java.util
        include:
          - java: '17'
            maven-opts: --add-opens java.base/java.util=ALL-UNNAMED
            maven-params: ''
          - java: '20'
            maven-opts: --add-opens java.base/java.util=ALL-UNNAMED
            maven-params: ''
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.maven-opts }}
        run: mvn ${{ matrix.maven-params }} test javadoc:javadoc
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          annotate_notice: false
          check_name: Test report ${{ matrix.java }}
