name: Cluster IT - 1C3D

on:
  push:
    branches: [ iotdb ]
























jobs:
  Simple:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [ 8, 11, 17 ]
    runs-on: [self-hosted, iotdb]
#      group: self-hosted
#      labels: iotdb
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: IT/UT Test
        shell: bash
        # we do not compile client-cpp for saving time, it is tested in client.yml
        # we can skip influxdb-protocol because it has been tested separately in influxdb-protocol.yml
        run: |
          mvn clean verify \
          -P with-integration-tests \
          -DskipUTs \
          -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 \
          -pl integration-test \
          -am -PClusterIT
      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cluster-log-java${{ matrix.java }}-${{ runner.os }}
          path: integration-test/target/cluster-logs
          retention-days: 1
