name: Run Danger on PR

on:
  push:
    branches: [ react-native-macos ]











jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - uses: actions/checkout@v3
      - name: Run Yarn Install on Root
        run: yarn install
        working-directory: .
      - name: Danger
        run: yarn danger ci --use-github-checks --failOnErrors
        working-directory: packages/react-native-bots
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
