name: HandleStaleDiscussions
on:
  push:
    branches: [ aws-sdk-java-v2 ]





jobs:
  handle-stale-discussions:
    name: Handle stale discussions
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Stale discussions action
        uses: aws-github-ops/handle-stale-discussions@v1
        env:
          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
