name: Add support label to issue

on:
  push:
    branches: [ zeebe ]









jobs:
  check-and-add-support-label:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.2
      with:
        configuration-path: .github/issue-labeler.yml
        enable-versioned-regex: 0
        repo-token: "${{ github.token }}"
