name: Release Dry Run from main
on:
  push:
    branches: [ zeebe ]





jobs:
  dry-run-release:
    name: "${{ matrix.version }} from main"
    uses: ./.github/workflows/release.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        version: [ 0.8.2, 0.8.2-alpha1 ]
        include:
          - version: 0.8.2
            latest: true
          - version: 0.8.2-alpha1
            latest: false
    with:
      releaseBranch: main
      releaseVersion: ${{ matrix.version }}
      nextDevelopmentVersion: 0.0.0-SNAPSHOT
      isLatest: ${{ matrix.latest }}
      dryRun: true
  notify:
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [ dry-run-release ]
    if: ${{ always() }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    steps:
      - id: slack-notify-failure
        name: Send failure slack notification
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ always() && needs.dry-run-release.result != 'success' }}
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alarm: *Release Dry Run* from `main` failed! :alarm:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/zeebe/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
      - id: slack-notify-success
        name: Send success slack notification
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ always() && needs.dry-run-release.result == 'success' }}
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":tada: *Release Dry Run* from `main` succeeded! :tada:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Nothing to check today. Good job! :clap:\n"
                  }
                }
              ]
            }

