name: Validate Artifact Dependencies

on:
  push:
    branches: [ firebase-android-sdk ]





jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Perform gradle build
        run: |
          ./gradlew validatePomForRelease
